conventional-commits:
  - type: 'fix'
    nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
    labels: ['bug', 'versioning/patch']
  - type: 'feature'
    nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
    labels: ['enhancement', 'versioning/minor']
  - type: 'breaking_change'
    nouns: ['BREAKING CHANGE', 'BREAKING', 'BREAK', 'breaking change', 'breaking', 'break', 'MAJOR']
    labels: ['BREAKING CHANGE', 'versioning/major']
  - type: 'refactor'
    nouns: ['Refactor', 'Refact', 'Refac', 'refac', 'refact', 'refactor', 'REFAC', 'REFACT', 'REFACTOR', 'refacs', 'refacts', 'refactors', 'REFACS', 'REFACTS', 'REFACTORS']
    labels: ['refactor', 'versioning/patch']
  - type: 'dependencies'
    nouns: ['dependencies', 'dependencie', 'depends', 'depend', 'deps', 'dep', 'chore']
    labels: ['dependencies', 'versioning/patch']
  - type: 'build'
    nouns: ['build', 'rebuild']
    labels: ['build', 'versioning/patch']
  - type: 'builddeps'
    nouns: ['build(deps)', 'build(deps-dev)']
    labels: ['build', 'dependencies', 'versioning/patch']
  - type: 'documentation'
    nouns: ['doc', 'docs', 'docu', 'document', 'documentation']
    labels: ['documentation', 'versioning/patch']
  - type: 'config'
    nouns: ['config', 'conf', 'configs', 'confs', 'cofiguration', 'cofigurations', 'configure']
    labels: ['config', 'versioning/patch']
  - type: 'ci'
    nouns: ['ci', 'CI']
    labels: ['ci', 'versioning/patch']
  - type: 'test'
    nouns: ['test', 'tests', 'testing']
    labels: ['test']
  - type: 'wip'
    nouns: ['wip', 'WIP', 'Wip']
    labels: ['wip']
