name: Versioning Beta

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_call:
    inputs:
      branch:
        description: 'The branch where the versioning will be executed'
        type: string
        required: false
        default: 'main'
      majorList:
        description: 'List of the nouns that will be considered as major version'
        type: string
        required: false
        default: 'BREAKING CHANGE, BREAKING, MAJOR'
      minorList:
        description: 'List of the nouns that will be considered as minor version'
        type: string
        required: false
        default: 'FEATURE, Feature, feature, FEAT, Feat, feat'
      patchList:
        description: 'List of the nouns that will be considered as patch version'
        type: string
        required: false
        default: 'FIX, Fix, fix, FIXED, Fixed, fixed, Refactor, Refact, Refac, refac, refact, refactor, REFAC, REFACT, REFACTOR, refacs, refacts, refactors, REFACS, REFACTS, REFACTORS, config, conf, configs, confs, cofiguration, cofigurations, configure, doc, docs, docu, document, documentation, dependencies, dependencie, depends, depend, deps, dep, chore, build, rebuild, build(deps), build(deps-dev), ci, CI, test, tests, testing, wip, WIP, Wip'
    secrets:
      github-token:
        description: 'The Github token'
        required: true
    outputs:
      current:
        description: 'The current version'
        value: ${{ jobs.versioning.outputs.current }}
      next-patch:
        description: 'The next version with format v0.0.0'
        value: ${{ jobs.versioning.outputs.next-patch }}
      next-minor:
        description: 'The minor version with format v0.0'
        value: ${{ jobs.versioning.outputs.next-minor }}
      next-major:
        description: 'The major version with format v0'
        value: ${{ jobs.versioning.outputs.next-major }}

env:
  GH_TOKEN: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      current: ${{ steps.semver.outputs.current }}
      next-patch: ${{ steps.semver.outputs.next }}
      next-minor: ${{ steps.push.outputs.minor }}
      next-major: ${{ steps.push.outputs.major }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref || 'main' }}
          majorList: ${{ github.event.inputs.majorList || 'BREAKING CHANGE, BREAKING, MAJOR' }}
          minorList: ${{ github.event.inputs.minorList || 'FEATURE, Feature, feature, FEAT, Feat, feat' }}
          patchList: ${{ github.event.inputs.patchList || 'FIX, Fix, fix, FIXED, Fixed, fixed, Refactor, Refact, Refac, refac, refact, refactor, REFAC, REFACT, REFACTOR, refacs, refacts, refactors, REFACS, REFACTS, REFACTORS, config, conf, configs, confs, cofiguration, cofigurations, configure, doc, docs, docu, document, documentation, dependencies, dependencie, depends, depend, deps, dep, chore, build, rebuild, build(deps), build(deps-dev), ci, CI, test, tests, testing, wip, WIP, Wip' }}
          patchAll: false

      - name: Generate candidate tag
        id: candidate
        run: |
          #!/bin/sh

          # Generate the candidate tag
          candidate=${{ steps.semver.outputs.next }}.rc.${{ github.event.number }}
  
          # Output the candidate tag
          echo "candidate=$candidate" >> $GITHUB_ENV

      - name: Scan versioning sources
        id: scan
        run: |
          #!/bin/sh

          # Find the version.txt file
          versionTxt=$(find . -name version.txt)

          # Find the package.json file
          packageJson=$(find . -name package.json)

          # Find the .csproj files
          csproj=$(find . -name "*.csproj")

          echo "versionTxt=$versionTxt" >> $GITHUB_ENV
          echo "packageJson=$packageJson" >> $GITHUB_ENV
          echo "csproj=$csproj" >> $GITHUB_ENV

      - name: Update version number in version.txt
        if: steps.scan.outputs.versionTxt != ''
        run: |
          #!/bin/sh

          # update the version for each file
          sed -i "s/.*$/${{ steps.candidate.outputs.candidate }}/g" ${{ steps.scan.outputs.versionTxt }}

      - name: Update version number in package.json
        if: steps.scan.outputs.packageJson != ''
        run: |
          #!/bin/sh

          # update the version for each file found
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.candidate.outputs.candidate }}\"/g" ${{ steps.scan.outputs.packageJson }}          

      - name: Update version number in .Net projects
        if: steps.scan.outputs.csproj != ''
        run: |
          #!/bin/sh

          # update the version for each file found
          sed -i "s/<Version>.*<\/Version>/<Version>${{ steps.candidate.outputs.candidate }}<\/Version>/g" ${{ steps.scan.outputs.csproj }}

      - name: Commit changes
        id: commit
        if : steps.scan.outputs.versionTxt != '' || steps.scan.outputs.packageJson != '' || steps.scan.outputs.csproj != ''
        run: |
          #!/bin/sh

          # Commit the changes
          git add .
          git commit --amend --no-edit

      - name: tagger
        id: tagger
        run: |
          #!/bin/sh

          # Set new tags and force update
          git tag --force ${{ steps.candidate.outputs.candidate }}

      - name: Push tags
        id: push
        run: |
          #!/bin/sh

          # Push new tag forcing the update of the minor and major tag
          git push --tag --force

          # output major and minor tags
          echo "candidate=${{ steps.candidate.outputs.candidate }}" >> $GITHUB_OUTPUT
